//var dataset = [[6,5], [5,4],[8,6],[7,5],[3,3],[3,2],[7,9],[2,5]];
d3.select('body')
  .append('svg')
  .attr('width', 500)
  .attr('height',500)
  .attr('id', 'chart')

let chart = d3.select('#chart')
  .append('g')
  .attr('transform','translate(30,10)')
var margin = {top: 50, right: 20, bottom: 350, left: 30},
  width = 500- margin.left - margin.right,
  height = 500 - margin.top - margin.bottom;
var y = d3.scaleLinear()
    .domain([0,15])
    .range([height,0])
//let xScale = d3.scaleLinear()
  //.domain([0,20])
  //.range([0,200])
let yScale = d3.scaleLinear()
  .domain([0,15])
  .range([100,0])
 
d3.csv("./Data.csv").then( (forage) => {
    console.log(forage)
    chart.append('g')//first bar graph
    .selectAll('rect')
    .data(forage)
    .enter()
        .append('rect')
        .attr('x', d => -35 + 40*d.ID)
        .attr('y',d => yScale(d.data1))
        .attr('width',10)
        .attr('height',d =>height - y(d.data1))
        .style('fill','black')
    
     chart.append('g')//second bar graph
     .selectAll('rect')
     .data(forage)
     .enter()
         .append('rect')
         .attr('x', d => -25 + 40*d.id)
         .attr('y',d => yScale(d.data2))
         .attr('width',10)
         .attr('height',d =>height - y(d.data2))
         .style('fill','Red')
     
    let xLabels = chart.append('g')
         .selectAll('text')
         .data(forage)
  
      xLabels
         .enter()
              .append('text')
              .attr('font-size','12px')
              .attr('font-family','Arial')
              .style("text-anchor","middle")
              .attr('transform', d => `translate(${-25 + 40*d.id}, 120)`) // , rotate(-30)
              .attr('x', 0)
              .attr('y', 0)
              .text(d => { return [d.Days] } )
      // xLabels 
      //         .selectAll('text')
      //         .data(forage)
      //         .text(d => d)
      //         .attr('transform', 'translate(-20 -20) rotate(-30)')
let name= chart.append('text')
    .attr('transform', 'translate(160,150)')
      .text('Video Type')
      .style("text-anchor","middle")
      .attr('font-size','12px')
      .attr('fill','black')
let name2= chart.append('text')
    .attr('transform', 'translate(350,60) rotate(90)')
      .text('Total Videos')
      .attr('font-size','12px')
      .style("text-anchor","middle")
      .attr('fill','black')

let stickers = chart.append('text')
        .text("Entertainment")
        .attr('x', 280)
        .attr('y', 15)
        .style('fill', 'black')
        .attr('font-size','8px')
let stickers2 = chart.append('text')
        .text("Educational")
        .attr('x', 280)
        .attr('y', 30)
        .style('fill', 'red')
        .attr('font-size','8px')
})

chart.append('g')
    //.attr('transform', 'translate(10, 100)')
    .call(d3.axisLeft(yScale).ticks(5))
